# Generated by Django 3.0.4 on 2020-03-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
