# Generated by Django 3.0.4 on 2020-03-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
