# Generated by Django 3.0.4 on 2020-03-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_topic_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
