# Generated by Django 3.0.4 on 2020-03-22 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200312_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_from', to='board.Topic')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='board.Topic')),
            ],
        ),
    ]
